### ISSUE TITLE
Pages missing.

### ISSUE THREAD

**Issue by DukeTheBadDragon** [andrewlalis/BlockBookBinder#5]
It worked correctly the first time but now keeps missing the same pages over and over again. I have no idea whats going on.

**Comment by andrewlalis** [comment]
Probably the performance of your pc and/or server is to blame. Increase the amount of delay between pages. Also include more information about your hardware, java version, mc version, etc, otherwise I can't really help.

**Comment by EphraimBane** [comment]
From my testing this appears to be due to the missing pages being overfilled, as removing some characters manually from the missing pages allows them to be pasted. This should be easily fixable with a rework of font size handling, or as a temporary fix, an option for max amount of characters per page.

**Comment by andrewlalis** [comment]
@EphraimBane can you attach some sample text which you have found to cause the overfilling? Then I can try to adjust the character sizing requirements, as something must have changed in a recent Minecraft version to make the spacing no longer work.

**Comment by andrewlalis** [comment]
Closing this because it can be manually addressed by users in #8
